# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-03 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='date',
            field=models.DateField(),
        ),
    ]
