# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.CharField(choices=[('PRODUCT', 'PRODUCT'), ('CLIENT', 'CLIENT'), ('REGION', 'REGION'), ('SALESMAN', 'SALESMAN')], default='PRIMARY', max_length=20)),
                ('number', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='volume',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='volume',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salesman',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salesman',
            name='volume',
            field=models.FloatField(default=0),
        ),
    ]
