# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='salesman',
            name='company',
        ),
        migrations.AlterField(
            model_name='region',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=23.777176, max_digits=9),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=90.399452, max_digits=9),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='t_type',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Discount', 'Discount'), ('Return', 'Return')], default='Primary', max_length=20),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
