# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180221_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='t_type',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Discount', 'Discount'), ('Return', 'Return'), ('PURCHASE', 'PURCHASE')], default='Primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Client'),
        ),
    ]
