# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-03 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180203_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='volume',
        ),
    ]
