# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180221_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='volume',
            field=models.FloatField(default=0),
        ),
    ]
