# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-03 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180203_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SalesMan'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voucher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Voucher'),
        ),
    ]
