# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180221_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='t_type',
            field=models.CharField(choices=[('PRIMARY', 'PRIMARY'), ('DISCOUNT', 'DISCOUNT'), ('RETURN', 'RETURN'), ('PURCHASE', 'PURCHASE')], default='PRIMARY', max_length=20),
        ),
    ]
